### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [drgrigg/thomas-paine_the-rights-of-man#1]
Part 2, Chapter 5:
- [ ] I think the tables should go inside the `<div>`s since the headers belong to the tables, like how we use `<blockquote>`s.

- [ ] The table headers in Table 3 are all on the left side of the table.

**Comment by drgrigg** [comment]
I agree about the divs. Fixed the problem with the column headers in Table III and added a little more CSS to make the footer look better.
